language: python
sudo: false
cache: pip

python:
  - '3.4'
  - '3.5'
  - '3.6'

before_install:
  - openssl aes-256-cbc -K $encrypted_12e75a453f27_key -iv $encrypted_12e75a453f27_iv -in gcs-service-account.json.enc -out gcs-service-account.json -d

install:
  - pip install --upgrade setuptools
  - pip install tox-travis

script: tox

env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=flake8
  - TOXENV=docs
