sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install: pip install tox-travis
script: tox
env:
  global:
  - RACKSPACE_REGION=IAD
  - secure: Ce2HF5k15EI76rCarDvI2BSYEZIDOTsOA+CefMI+IIhAhcyj4Y/Ti54KQLEK2rEOOV/HLu4MZJqG/Gq4pmhim5JnNWFdvW/YzvFMrK3kZ/2VVV9C3VTiQIovsnHtad8gUBbMupSzwxhsO/dlyw/Nrplhwa4/y23XkrLvC0Kd0oZPhp3hEB+UtOx4T4OyNG43+TJvvxakbntsFBGbnK7LTyhwFMtycK/Un0fykvwPWSHD2QniD22oA0FnqsdT0ynK4t5cu61REtZSXZd0VpGmJBtDKSdCbIcQ94nbO0MwWK76c+9+z7pZcabt2dwsShg+6NxdEMA1VYm7L1xNgzeZlrOsqMJyMUvgQY6wO3BmMsOCekPSTAEo2HR13nloudxjeJHdrWyIHv1XvAyntHGKxvvDICZGNIk+P1uGPJCmZdKiPLNo0LQZAM134sLGW1WFgL2xCZeIHEGVpQUfSppnojWZRawL/+zuH+mmtBeIHbrvVA3cZ5/Sxzwd2MnehQtFj8peEybJW1QiZejAtqnykv+ZD1S8T1DuLjykthlfmDeW3vMD1aReAVItH47WNspWvs155HFqtQq5TFVJDAzVMyLf/OaZXNgiSUJy9dPOIczQ+4Tlv8k1FiON//YfX/63o53ufZtgm90IXNHYU2FfRPJDdbjJuXSgsvSu1pMgS/k=
  - secure: YiGkfgkfrYL2uQ+t3FZW7tZZGj3WzPoHIaTyiO8h/KS3Zj/SF6yuiRJlYTO4r73/nt4+wbPrz+HWJ4mz6Mtz4ygAUlzuLQZDc/N+ZSeRs/zgtv9QnPcLhq4NlYlbU2aNp6rJAi4FnIKsv0JEsEO2+5khubwkAX/OoVr+FYgdEYr5hRuA2wm279m2S6lj1Uw41z0weXAstsD0w4Fs9PB5TP7o57H/Nc/tnmoOlI+3+knMr8ijqHNLT04ALCUjdfj33FzLZLItDSI2NrtJlGABjH5Dx1yL9aI6+q2EJP1ZwjAPTTvXMs8Pn+iYuMxaQ6oFmTY1zgE3bM2RITLuNhHMS13ORjaKxYiyJQjdVBQOGH9WiUc/7oXd0CS5rq/qlk/fclCPbJcqFmikx5omcUFA9dSDGoZ3gSi0vuNHrEmRbqjsnHCzjVXahhCfydL/BCFT8mgiGCil46ldBgeEtCacTYw7Srm26FXnaZx+XnTkLm8hNmVgsu+l5H+w4ZYs5IoTypwf2ikJQTZebfL/oI9tE8lYdh/RAnCT4hRrg0i9lczcpNPZc7JvzC84e9rj28ehrd4esKeiW4AzN8VgqqFZ/s7QMM6p8mVg6nVSWny/zSUd7erRXB+5fERqxZePgoI2HdAPHDLE1oMUSabMu0Dsbu5ahUI4TQa7m0ZJfr96OW4=
